"""init bronze silver gold

Revision ID: 19973427db31
Revises: 
Create Date: 2026-05-08 12:20:16.542654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19973427db31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_snapshots',
    sa.Column('bronze_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bronze_id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_api_snapshots_fetched_at'), 'api_snapshots', ['fetched_at'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_api_snapshots_parsed_at'), 'api_snapshots', ['parsed_at'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_api_snapshots_source'), 'api_snapshots', ['source'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_api_snapshots_source_url'), 'api_snapshots', ['source_url'], unique=False, schema='bronze')
    op.create_table('html_snapshots',
    sa.Column('bronze_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html', sa.LargeBinary(), nullable=False),
    sa.Column('is_diff', sa.Boolean(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bronze_id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_html_snapshots_fetched_at'), 'html_snapshots', ['fetched_at'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_html_snapshots_parsed_at'), 'html_snapshots', ['parsed_at'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_html_snapshots_source'), 'html_snapshots', ['source'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_html_snapshots_source_url'), 'html_snapshots', ['source_url'], unique=False, schema='bronze')
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_html', sa.String(), nullable=True),
    sa.Column('body_text', sa.String(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_articles_source_url'),
    schema='silver'
    )
    op.create_index(op.f('ix_silver_articles_published_at'), 'articles', ['published_at'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_articles_source'), 'articles', ['source'], unique=False, schema='silver')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_products_source_url'),
    schema='silver'
    )
    op.create_index(op.f('ix_silver_products_observed_at'), 'products', ['observed_at'], unique=False, schema='silver')
    op.create_index(op.f('ix_silver_products_source'), 'products', ['source'], unique=False, schema='silver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_products_source'), table_name='products', schema='silver')
    op.drop_index(op.f('ix_silver_products_observed_at'), table_name='products', schema='silver')
    op.drop_table('products', schema='silver')
    op.drop_index(op.f('ix_silver_articles_source'), table_name='articles', schema='silver')
    op.drop_index(op.f('ix_silver_articles_published_at'), table_name='articles', schema='silver')
    op.drop_table('articles', schema='silver')
    op.drop_index(op.f('ix_bronze_html_snapshots_source_url'), table_name='html_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_html_snapshots_source'), table_name='html_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_html_snapshots_parsed_at'), table_name='html_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_html_snapshots_fetched_at'), table_name='html_snapshots', schema='bronze')
    op.drop_table('html_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_api_snapshots_source_url'), table_name='api_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_api_snapshots_source'), table_name='api_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_api_snapshots_parsed_at'), table_name='api_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_api_snapshots_fetched_at'), table_name='api_snapshots', schema='bronze')
    op.drop_table('api_snapshots', schema='bronze')
    # ### end Alembic commands ###
