"""silver bronze_id provenance; drop dedup constraint

Revision ID: 2f57267f8db7
Revises: 9e1e821059eb
Create Date: 2026-05-11 11:58:45.982745

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f57267f8db7"
down_revision: str | Sequence[str] | None = "9e1e821059eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("bronze_id", sa.Integer(), nullable=False), schema="silver")
    op.drop_constraint(op.f("uq_articles_source_url"), "articles", schema="silver", type_="unique")
    op.create_index(
        op.f("ix_silver_articles_bronze_id"),
        "articles",
        ["bronze_id"],
        unique=False,
        schema="silver",
    )
    op.drop_column("articles", "updated_at", schema="silver")
    op.add_column("products", sa.Column("bronze_id", sa.Integer(), nullable=False), schema="silver")
    op.drop_constraint(op.f("uq_products_source_url"), "products", schema="silver", type_="unique")
    op.create_index(
        op.f("ix_silver_products_bronze_id"),
        "products",
        ["bronze_id"],
        unique=False,
        schema="silver",
    )
    op.drop_column("products", "updated_at", schema="silver")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        schema="silver",
    )
    op.drop_index(op.f("ix_silver_products_bronze_id"), table_name="products", schema="silver")
    op.create_unique_constraint(
        op.f("uq_products_source_url"),
        "products",
        ["source", "source_url"],
        schema="silver",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("products", "bronze_id", schema="silver")
    op.add_column(
        "articles",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        schema="silver",
    )
    op.drop_index(op.f("ix_silver_articles_bronze_id"), table_name="articles", schema="silver")
    op.create_unique_constraint(
        op.f("uq_articles_source_url"),
        "articles",
        ["source", "source_url"],
        schema="silver",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("articles", "bronze_id", schema="silver")
    # ### end Alembic commands ###
