"""silver: drop body_html, rename body_text to body, currency default PYG, drop in_stock

Revision ID: 6fc47caa4d15
Revises: e795ac070b5e
Create Date: 2026-05-11 14:43:40.189508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fc47caa4d15"
down_revision: str | Sequence[str] | None = "e795ac070b5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("body", sa.String(), nullable=True), schema="silver")
    op.drop_column("articles", "body_html", schema="silver")
    op.drop_column("articles", "body_text", schema="silver")
    op.alter_column(
        "products", "currency", existing_type=sa.VARCHAR(), nullable=False, schema="silver"
    )
    op.drop_column("products", "in_stock", schema="silver")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("in_stock", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="silver",
    )
    op.alter_column(
        "products", "currency", existing_type=sa.VARCHAR(), nullable=True, schema="silver"
    )
    op.add_column(
        "articles",
        sa.Column("body_text", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="silver",
    )
    op.add_column(
        "articles",
        sa.Column("body_html", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="silver",
    )
    op.drop_column("articles", "body", schema="silver")
    # ### end Alembic commands ###
