"""add_silver_provenance_timestamps

Revision ID: 9e1e821059eb
Revises: cd12f9294d7d
Create Date: 2026-05-11 10:13:18.727241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e1e821059eb"
down_revision: str | Sequence[str] | None = "cd12f9294d7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="silver",
    )
    op.add_column(
        "articles",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="silver",
    )
    op.add_column(
        "products",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="silver",
    )
    op.add_column(
        "products",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="silver",
    )
    op.drop_index(op.f("ix_silver_products_observed_at"), table_name="products", schema="silver")
    op.drop_column("products", "observed_at", schema="silver")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("observed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        schema="silver",
    )
    op.create_index(
        op.f("ix_silver_products_observed_at"),
        "products",
        ["observed_at"],
        unique=False,
        schema="silver",
    )
    op.drop_column("products", "updated_at", schema="silver")
    op.drop_column("products", "created_at", schema="silver")
    op.drop_column("articles", "updated_at", schema="silver")
    op.drop_column("articles", "created_at", schema="silver")
    # ### end Alembic commands ###
