"""add bronze unique natural key

Revision ID: b064d9b482de
Revises: 19973427db31
Create Date: 2026-05-08 13:22:28.347159

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b064d9b482de"
down_revision: str | Sequence[str] | None = "19973427db31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_api_snapshots_natural_key",
        "api_snapshots",
        ["source", "source_url", "fetched_at"],
        schema="bronze",
    )
    op.create_unique_constraint(
        "uq_html_snapshots_natural_key",
        "html_snapshots",
        ["source", "source_url", "fetched_at"],
        schema="bronze",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_html_snapshots_natural_key", "html_snapshots", schema="bronze", type_="unique"
    )
    op.drop_constraint(
        "uq_api_snapshots_natural_key", "api_snapshots", schema="bronze", type_="unique"
    )
    # ### end Alembic commands ###
