"""bronze_drop_parsed_at_rename_fetched_at_to_created_at

Revision ID: cd12f9294d7d
Revises: b064d9b482de
Create Date: 2026-05-09 17:23:10.763516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd12f9294d7d"
down_revision: str | Sequence[str] | None = "b064d9b482de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_snapshots",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="bronze",
    )
    op.drop_index(
        op.f("ix_bronze_api_snapshots_fetched_at"), table_name="api_snapshots", schema="bronze"
    )
    op.drop_index(
        op.f("ix_bronze_api_snapshots_parsed_at"), table_name="api_snapshots", schema="bronze"
    )
    op.drop_constraint(
        op.f("uq_api_snapshots_natural_key"), "api_snapshots", schema="bronze", type_="unique"
    )
    op.create_unique_constraint(
        "uq_api_snapshots_natural_key",
        "api_snapshots",
        ["source", "source_url", "created_at"],
        schema="bronze",
    )
    op.create_index(
        op.f("ix_bronze_api_snapshots_created_at"),
        "api_snapshots",
        ["created_at"],
        unique=False,
        schema="bronze",
    )
    op.drop_column("api_snapshots", "fetched_at", schema="bronze")
    op.drop_column("api_snapshots", "parsed_at", schema="bronze")
    op.add_column(
        "html_snapshots",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="bronze",
    )
    op.drop_index(
        op.f("ix_bronze_html_snapshots_fetched_at"), table_name="html_snapshots", schema="bronze"
    )
    op.drop_index(
        op.f("ix_bronze_html_snapshots_parsed_at"), table_name="html_snapshots", schema="bronze"
    )
    op.drop_constraint(
        op.f("uq_html_snapshots_natural_key"), "html_snapshots", schema="bronze", type_="unique"
    )
    op.create_unique_constraint(
        "uq_html_snapshots_natural_key",
        "html_snapshots",
        ["source", "source_url", "created_at"],
        schema="bronze",
    )
    op.create_index(
        op.f("ix_bronze_html_snapshots_created_at"),
        "html_snapshots",
        ["created_at"],
        unique=False,
        schema="bronze",
    )
    op.drop_column("html_snapshots", "fetched_at", schema="bronze")
    op.drop_column("html_snapshots", "parsed_at", schema="bronze")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "html_snapshots",
        sa.Column("parsed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        schema="bronze",
    )
    op.add_column(
        "html_snapshots",
        sa.Column("fetched_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        schema="bronze",
    )
    op.drop_index(
        op.f("ix_bronze_html_snapshots_created_at"), table_name="html_snapshots", schema="bronze"
    )
    op.drop_constraint(
        "uq_html_snapshots_natural_key", "html_snapshots", schema="bronze", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_html_snapshots_natural_key"),
        "html_snapshots",
        ["source", "source_url", "fetched_at"],
        schema="bronze",
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_bronze_html_snapshots_parsed_at"),
        "html_snapshots",
        ["parsed_at"],
        unique=False,
        schema="bronze",
    )
    op.create_index(
        op.f("ix_bronze_html_snapshots_fetched_at"),
        "html_snapshots",
        ["fetched_at"],
        unique=False,
        schema="bronze",
    )
    op.drop_column("html_snapshots", "created_at", schema="bronze")
    op.add_column(
        "api_snapshots",
        sa.Column("parsed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        schema="bronze",
    )
    op.add_column(
        "api_snapshots",
        sa.Column("fetched_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        schema="bronze",
    )
    op.drop_index(
        op.f("ix_bronze_api_snapshots_created_at"), table_name="api_snapshots", schema="bronze"
    )
    op.drop_constraint(
        "uq_api_snapshots_natural_key", "api_snapshots", schema="bronze", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_api_snapshots_natural_key"),
        "api_snapshots",
        ["source", "source_url", "fetched_at"],
        schema="bronze",
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_bronze_api_snapshots_parsed_at"),
        "api_snapshots",
        ["parsed_at"],
        unique=False,
        schema="bronze",
    )
    op.create_index(
        op.f("ix_bronze_api_snapshots_fetched_at"),
        "api_snapshots",
        ["fetched_at"],
        unique=False,
        schema="bronze",
    )
    op.drop_column("api_snapshots", "created_at", schema="bronze")
    # ### end Alembic commands ###
