"""silver: products.currency server_default PYG

Revision ID: d9d2543af773
Revises: 72a47d6dcfb2
Create Date: 2026-05-18 14:21:54.440919

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9d2543af773"
down_revision: str | Sequence[str] | None = "72a47d6dcfb2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "currency",
        existing_type=sa.VARCHAR(),
        server_default="PYG",
        existing_nullable=False,
        schema="silver",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "currency",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
        schema="silver",
    )
    # ### end Alembic commands ###
