"""drop bronze natural-key unique constraints

Revision ID: e795ac070b5e
Revises: 2f57267f8db7
Create Date: 2026-05-11 13:42:36.604350

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e795ac070b5e"
down_revision: str | Sequence[str] | None = "2f57267f8db7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_api_snapshots_natural_key"), "api_snapshots", schema="bronze", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_html_snapshots_natural_key"), "html_snapshots", schema="bronze", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_html_snapshots_natural_key"),
        "html_snapshots",
        ["source", "source_url", "created_at"],
        schema="bronze",
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_api_snapshots_natural_key"),
        "api_snapshots",
        ["source", "source_url", "created_at"],
        schema="bronze",
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
