"""gold dim_product and fact_price

Revision ID: e9e57b12d2c7
Revises: ef9609c8eb63
Create Date: 2026-06-01 10:55:32.702455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9e57b12d2c7'
down_revision: Union[str, Sequence[str], None] = 'ef9609c8eb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_product',
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), server_default='PYG', nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('product_key'),
    sa.UniqueConstraint('source', 'sku', name='uq_dim_product_source_sku'),
    schema='gold'
    )
    op.create_index(op.f('ix_gold_dim_product_source'), 'dim_product', ['source'], unique=False, schema='gold')
    op.create_table('fact_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default='PYG', nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('bronze_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_key'], ['gold.dim_product.product_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_key', 'observed_at', name='uq_fact_price_product_observed'),
    schema='gold'
    )
    op.create_index(op.f('ix_gold_fact_price_product_key'), 'fact_price', ['product_key'], unique=False, schema='gold')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_fact_price_product_key'), table_name='fact_price', schema='gold')
    op.drop_table('fact_price', schema='gold')
    op.drop_index(op.f('ix_gold_dim_product_source'), table_name='dim_product', schema='gold')
    op.drop_table('dim_product', schema='gold')
    # ### end Alembic commands ###
