"""add bronze.failed_snapshots dead-letter table

Revision ID: ef9609c8eb63
Revises: 27135a17b755
Create Date: 2026-05-21 10:55:47.414802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9609c8eb63'
down_revision: Union[str, Sequence[str], None] = '27135a17b755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='bronze'
    )
    op.create_index(op.f('ix_bronze_failed_snapshots_created_at'), 'failed_snapshots', ['created_at'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_failed_snapshots_request_url'), 'failed_snapshots', ['request_url'], unique=False, schema='bronze')
    op.create_index(op.f('ix_bronze_failed_snapshots_source'), 'failed_snapshots', ['source'], unique=False, schema='bronze')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bronze_failed_snapshots_source'), table_name='failed_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_failed_snapshots_request_url'), table_name='failed_snapshots', schema='bronze')
    op.drop_index(op.f('ix_bronze_failed_snapshots_created_at'), table_name='failed_snapshots', schema='bronze')
    op.drop_table('failed_snapshots', schema='bronze')
    # ### end Alembic commands ###
