name: biggie
log_level: INFO
extract:
  scraper: supermercados.biggie
  base_url: https://api.app.biggie.com.py/api/articles
  allowed_domains:
  - api.app.biggie.com.py
  scrape_patterns: []
  ignore_patterns: []
  max_pages: -1
  concurrency: 5
  timeout_seconds: 30.0
  request_delay: 0.5
transform:
  parser: supermercados.biggie
