name: biggie
log_level: INFO
extract:
  scraper: supermercados.biggie
  timeout_seconds: 30.0
  concurrency: 5
  params:
    take: '100'
  base_url: https://api.app.biggie.com.py/api/articles
  scrape_patterns: []
  ignore_patterns: []
  page_size: 100
  max_pages: -1
  request_delay: 0.5
  allowed_domains:
  - api.app.biggie.com.py
transform:
  parser: supermercados.biggie
