name: elnacional
log_level: INFO
extract:
  scraper: noticias.elnacional
  timeout_seconds: 30.0
  concurrency: 5
  base_url: https://www.elnacional.com.py
  scrape_patterns:
  - -n\d+(?:/|\?|#|$)
  ignore_patterns:
  - /tags/
  - /autor/
  - /multimedia/
  - /galeria/
  page_size: 0
  max_pages: -1
  allowed_domains:
  - www.elnacional.com.py
transform:
  parser: noticias.elnacional
