name: elnacional
log_level: INFO
extract:
  scraper: noticias.elnacional
  base_url: https://elnacional.com.py
  allowed_domains:
  - elnacional.com.py
  scrape_patterns:
  - -n\d+(?:/|\?|#|$)
  ignore_patterns:
  - /tags/
  - /autor/
  - /multimedia/
  - /galeria/
  max_pages: -1
  concurrency: 5
  timeout_seconds: 30.0
transform:
  parser: noticias.elnacional
