name: grutter
log_level: INFO
extract:
  scraper: supermercados.grutter
  timeout_seconds: 30.0
  concurrency: 5
  params:
    per_page: "100"
  options:
    base_url: https://grutteronline.casagrutter.com.py/wp-json/wc/store/v1/products
    scrape_url_patterns: []
    ignore_url_patterns: []
    page_size: 100
    max_pages: 0
    request_delay: 1.0
transform:
  parser: supermercados.grutter
  options: {}
