name: hoy
log_level: INFO
extract:
  scraper: noticias.hoy
  timeout_seconds: 30.0
  concurrency: 5
  params:
    per_page: '100'
    _embed: 'true'
  base_url: https://www.hoy.com.py/wp-json/wp/v2/posts
  scrape_patterns: []
  ignore_patterns: []
  page_size: 100
  max_pages: 10
  allowed_domains:
  - www.hoy.com.py
transform:
  parser: noticias.hoy
