name: lanacion
log_level: INFO
extract:
  scraper: noticias.lanacion
  timeout_seconds: 30.0
  concurrency: 5
  base_url: https://www.lanacion.com.py/pf/api/v3/content/fetch/content-search-feed-full
  scrape_patterns: []
  ignore_patterns: []
  page_size: 100
  max_pages: 10
  allowed_domains:
  - www.lanacion.com.py
transform:
  parser: noticias.lanacion
