name: npy
log_level: INFO
extract:
  scraper: noticias.npy
  base_url: https://www.npy.com.py
  allowed_domains:
  - www.npy.com.py
  scrape_patterns:
  - npy\.com\.py/noticias/.+/[^/]+-[^/]+-[^/]+-[^/]+
  ignore_patterns: []
  max_pages: -1
  concurrency: 3
  request_delay: 5
  timeout_seconds: 30.0
transform:
  parser: noticias.npy
