name: realonline
log_level: INFO
extract:
  scraper: supermercados.realonline
  base_url: https://nextgentheadless.instaleap.io/api/v3
  allowed_domains:
  - nextgentheadless.instaleap.io
  scrape_patterns: []
  ignore_patterns: []
  max_pages: -1
  concurrency: 5
  timeout_seconds: 30.0
  request_delay: 0.5
  headers:
    User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Apikey: a7c861b2-91f5-4105-a423-6b84f35247de
transform:
  parser: supermercados.realonline
load:
  builder: supermercados.product
