name: stock
log_level: INFO
extract:
  scraper: supermercados.stock
  timeout_seconds: 30.0
  concurrency: 5
  base_url: https://www.stock.com.py
  scrape_patterns:
  - /products/\d+[^/]*\.aspx(?:\?|#|$)
  ignore_patterns:
  - /account\.aspx
  - /register
  - /shoppingcart
  - /login
  - /contactus
  - /AboutUs
  - /NewsArchive
  - /topic/
  - /manufacturer/
  - /search
  - /customer/
  - \?pageindex=
  - \?idFiltro=
  max_pages: -1
  allowed_domains:
  - www.stock.com.py
transform:
  parser: supermercados.stock
