source: superseis
scraper:
  home_url: https://www.superseis.com.py
  scrape_pattern: "/product/"
  max_pages: 40000
  ignore_patterns:
    - /login
    - /cart
    - /account
    - /checkout
    - /register
    - /information/
    - /noticias
    - /ofertas$
    - /marcas$
    - /sucursales$
    - \?.*brands=
    - \?.*discounts=
    - /product/[^/?]+/
    - \?.*page=
