services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: supermercados
      POSTGRES_PASSWORD: supermercados
      POSTGRES_DB: supermercados
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/01-init.sql

volumes:
  pgdata:
